site_name: Init Commerce Flutter UI Kit docs
theme:
  name: material
nav:
    - Home: index.md
    - Setup enviroment: setup-enviroment.md
    - Project structure: project-structure.md
    - Module structure: module-structure.md
    - Customization: customization.md
    - Adding a new feature: add-new-feature.md
    - Adding a new language: add-new-language.md
    - Running the App: running-the-app.md
    - About: about.md
